title: CWCT System Administration
email: napoleon_soro@rocketmail.com
description: Mark Soro Cybersecurity Workforce Certification Training Program
baseurl: "/System_Administration_Cybersecurity_Workforce_Certification_Training/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  m-soro
social:
  name: Mark Soro
  links:
    - https://www.linkedin.com/in/marksoro
    - https://github.com/m-soro
    - https://www.facebook.com/msoro1

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag

ga_tracking: G-C2T4TD1526
